name: Code Checks
on:
  push:
  pull_request:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: 'poetry'
    - name: Install Dependencies
      run: poetry install
    - name: Pylint (dslinter)
      run: poetry run pylint src
    - name: flake8
      run: poetry run flake8 src
    - name: pydocstyle
      run: poetry run pydocstyle src
    - name: Bandit
      run: poetry run bandit -r src -c bandit.yaml
    - name: Test
      run: poetry run pytest
